JoaoSite/JoaoSite/Models/Anuncio.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace JoaoSite.Models
{
    public class Anuncio
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Modelo do veículo é obrigatório")]
        public int ModeloId { get; set; }

        [Required(ErrorMessage = "Valor de compra é obrigatório")]
        public decimal ValorCompra { get; set; }

        [Required(ErrorMessage = "Valor de venda é obrigatório")]
        public decimal ValorVenda { get; set; }

        [Required(ErrorMessage = "Cor é um campo obrigatório")]
        public string Cor { get; set; }

        [Required(ErrorMessage = "Combustível é um campo obrigatório")]
        public string Combustivel { get; set; }

        [Required(ErrorMessage = "Data da venda é obrigatório")]
        public DateTime DataVenda { get; set; }
    }
}

JoaoSite/JoaoSite/Controllers/AnuncioController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using JoaoSite.Context;
using JoaoSite.Models;
using PagedList;
using Rotativa;

namespace JoaoSite.Controllers
{
    public class AnuncioController : Controller
    {
        private readonly AppDbContext _context;

        public AnuncioController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Anuncio
        public async Task<IActionResult> Index()
        {
            return View(await _context.Anuncios.ToListAsync());
        }

        // GET: Anuncio/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var anuncio = await _context.Anuncios
                .FirstOrDefaultAsync(m => m.Id == id);
            if (anuncio == null)
            {
                return NotFound();
            }

            return View(anuncio);
        }

        // GET: Anuncio/Create
        public IActionResult Create()
        {
            ViewBag.Modelo = _context.Modelos;
            return View();
        }

        // POST: Anuncio/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ModeloId,ValorCompra,ValorVenda,Cor,Combustivel,DataVenda")] Anuncio anuncio)
        {
            if (ModelState.IsValid)
            {
                _context.Add(anuncio);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(anuncio);
        }

        // GET: Anuncio/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var anuncio = await _context.Anuncios.FindAsync(id);
            if (anuncio == null)
            {
                return NotFound();
            }

            ViewBag.Modelo = _context.Modelos.Where(a => a.Id == anuncio.ModeloId);

            return View(anuncio);
        }

        // POST: Anuncio/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ModeloId,ValorCompra,ValorVenda,Cor,Combustivel,DataVenda")] Anuncio anuncio)
        {
            if (id != anuncio.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(anuncio);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AnuncioExists(anuncio.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(anuncio);
        }

        // GET: Anuncio/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var anuncio = await _context.Anuncios
                .FirstOrDefaultAsync(m => m.Id == id);
            if (anuncio == null)
            {
                return NotFound();
            }

            return View(anuncio);
        }

        // POST: Anuncio/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var anuncio = await _context.Anuncios.FindAsync(id);
            _context.Anuncios.Remove(anuncio);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AnuncioExists(int id)
        {
            return _context.Anuncios.Any(e => e.Id == id);
        }
    }
}

JoaoSite/JoaoSite/Controllers/RelatorioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using JoaoSite.Context;
using JoaoSite.Models;
using Microsoft.AspNetCore.Mvc;
using PagedList;
using Rotativa;
using Rotativa.AspNetCore;

namespace JoaoSite.Controllers
{
    public class RelatorioController : Controller
    {
        private readonly AppDbContext _context;

        public RelatorioController(AppDbContext contexto)
        {
            _context = contexto;
        }

        [HttpPost]
        public ViewAsPdf RelatorioPedidos(string dataInicial, string dataFinal)
        {
            int pagNumero = 1;
            var relatorioPDF = new ViewAsPdf();
            relatorioPDF.ViewName = "RelatorioPedidos";
            relatorioPDF.FileName = "RelatorioPedidos.pdf";
            relatorioPDF.IsGrayScale = true;

            var listaAnuncios = _context.Anuncios.Where(a => a.DataVenda >= Convert.ToDateTime(dataInicial) && a.DataVenda <= Convert.ToDateTime(dataFinal)).OrderBy(c => c.ModeloId).ToList();

            if (listaAnuncios.Count() <= 0)
            {
                Anuncio anuncio = new Anuncio();
                anuncio.ModeloId = 999;
                anuncio.ValorVenda = 0;
                anuncio.ValorCompra = 0;
                listaAnuncios.Add(anuncio);
            }
            
            relatorioPDF.Model = listaAnuncios.ToPagedList(pagNumero, listaAnuncios.Count);
            return relatorioPDF;

        }
    }
}

JoaoSite/JoaoSite/Views/Anuncio/Create.cshtml
@model JoaoSite.Models.Anuncio

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Anuncio</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ModeloId" class="control-label"></label>
                <select asp-for="ModeloId" class="form-control">
                    @foreach (var item in ViewBag.Modelo)
                    {
                        <option value="@item.Id">@item.Id - @item.Descricao</option>
                    }
                </select>
                <span asp-validation-for="ModeloId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ValorCompra" class="control-label"></label>
                <input asp-for="ValorCompra" class="form-control" />
                <span asp-validation-for="ValorCompra" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ValorVenda" class="control-label"></label>
                <input asp-for="ValorVenda" class="form-control" />
                <span asp-validation-for="ValorVenda" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cor" class="control-label"></label>
                <input asp-for="Cor" class="form-control" />
                <span asp-validation-for="Cor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Combustivel" class="control-label"></label>
                <input asp-for="Combustivel" class="form-control"/>
                <span asp-validation-for="Combustivel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataVenda" class="control-label"></label>
                <input asp-for="DataVenda" class="form-control" />
                <span asp-validation-for="DataVenda" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

JoaoSite/JoaoSite/Views/Anuncio/Delete.cshtml
@model JoaoSite.Models.Anuncio

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Anuncio</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModeloId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModeloId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ValorCompra)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ValorCompra)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ValorVenda)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ValorVenda)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Combustivel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Combustivel)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataVenda)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataVenda)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

JoaoSite/JoaoSite/Views/Anuncio/Details.cshtml
@model JoaoSite.Models.Anuncio

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Anuncio</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModeloId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModeloId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ValorCompra)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ValorCompra)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ValorVenda)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ValorVenda)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Combustivel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Combustivel)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataVenda)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataVenda)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

JoaoSite/JoaoSite/Views/Anuncio/Edit.cshtml
@model JoaoSite.Models.Anuncio

@{
    ViewData["Title"] = "Editar";
}

<h1>Editar</h1>

<h4>Anuncio</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="ModeloId" class="control-label"></label>
                <select asp-for="ModeloId" class="form-control">
                    @foreach (var item in ViewBag.Modelo)
                    {
                        <option value="@item.Id">@item.Id - @item.Descricao</option>
                    }
                </select>
                <span asp-validation-for="ModeloId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ValorCompra" class="control-label"></label>
                <input asp-for="ValorCompra" class="form-control" />
                <span asp-validation-for="ValorCompra" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ValorVenda" class="control-label"></label>
                <input asp-for="ValorVenda" class="form-control" />
                <span asp-validation-for="ValorVenda" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cor" class="control-label"></label>
                <input asp-for="Cor" class="form-control" />
                <span asp-validation-for="Cor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Combustivel" class="control-label"></label>
                <input asp-for="Combustivel" class="form-control" />
                <span asp-validation-for="Combustivel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataVenda" class="control-label"></label>
                <input asp-for="DataVenda" class="form-control" />
                <span asp-validation-for="DataVenda" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

JoaoSite/JoaoSite/Views/Anuncio/Index.cshtml
@model IEnumerable<JoaoSite.Models.Anuncio>

@{
    ViewData["Title"] = "Anuncios";
}

<h1>Anúncios</h1>

<p>
    <button type="button" class="btn btn-success" onclick="location.href='@Url.Action("Create","Anuncio")'">Criar Novo</button>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Modelo
            </th>
            <th>
                Valor de compra
            </th>
            <th>
                Valor de venda
            </th>
            <th>
                Cor
            </th>
            <th>
                Combustível
            </th>
            <th>
                Data da venda
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ModeloId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ValorCompra)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ValorVenda)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cor)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Combustivel)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataVenda)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Detalhes</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Deletar</a>
                </td>
            </tr>
        }
   
        @using (Html.BeginForm("RelatorioPedidos", "Relatorio", FormMethod.Post))
        {
            <tr>
                <td>
                    Data Inicial: <input type="date" name="dataInicial" id="dataInicial" />
                </td>
                <td>
                    Data Final: <input type="date" name="dataFinal" id="dataFinal" />
                </td>
            </tr>
            <tr>
                <td>
                    <button type="submit" class="btn btn-success">Gerar PDF</button>
                </td>
            </tr>
        }
    </tbody>
</table>