JoaoSite/JoaoSite/Models/Modelo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace JoaoSite.Models
{
    public class Modelo
    {
        public int Id { get; set; }
        public string Descricao { get; set; }
        public int AnoLancamento { get; set; }
        public int MarcaId { get; set; }
        public Estoque Quantidade { get; set; }
    }
}

JoaoSite/JoaoSite/Controllers/ModeloController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using JoaoSite.Context;
using JoaoSite.Models;

namespace JoaoSite.Controllers
{
    public class ModeloController : Controller
    {
        private readonly AppDbContext _context;

        public ModeloController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Modelo
        public async Task<IActionResult> Index()
        {
            return View(await _context.Modelos.ToListAsync());
        }

        // GET: Modelo/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var modelo = await _context.Modelos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (modelo == null)
            {
                return NotFound();
            }

            return View(modelo);
        }

        // GET: Modelo/Create
        public IActionResult Create()
        {
            ViewBag.Marcas = _context.Marcas;
            return View();
        }

        // POST: Modelo/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Descricao,AnoLancamento,MarcaId")] Modelo modelo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(modelo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(modelo);
        }

        // GET: Modelo/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var modelo = await _context.Modelos.FindAsync(id);
            if (modelo == null)
            {
                return NotFound();
            }

            ViewBag.Marcas = _context.Marcas;

            return View(modelo);
        }

        // POST: Modelo/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Descricao,AnoLancamento,MarcaId")] Modelo modelo)
        {
            if (id != modelo.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(modelo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ModeloExists(modelo.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(modelo);
        }

        // GET: Modelo/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var modelo = await _context.Modelos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (modelo == null)
            {
                return NotFound();
            }

            return View(modelo);
        }

        // POST: Modelo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var modelo = await _context.Modelos.FindAsync(id);
            _context.Modelos.Remove(modelo);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ModeloExists(int id)
        {
            return _context.Modelos.Any(e => e.Id == id);
        }
    }
}

JoaoSite/JoaoSite/Views/Modelo/Create.cshtml
@model JoaoSite.Models.Modelo

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Modelo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AnoLancamento" class="control-label"></label>
                <input asp-for="AnoLancamento" class="form-control" />
                <span asp-validation-for="AnoLancamento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MarcaId" class="control-label"></label>
                <select asp-for="MarcaId" class ="form-control">
                    @foreach (var item in ViewBag.Marcas)
                    {
                        <option value="@item.Id">@item.Id - @item.Descricao</option>
                    }
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

JoaoSite/JoaoSite/Views/Modelo/Delete.cshtml
@model JoaoSite.Models.Modelo

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Modelo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AnoLancamento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AnoLancamento)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

JoaoSite/JoaoSite/Views/Modelo/Details.cshtml
@model JoaoSite.Models.Modelo

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Modelo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AnoLancamento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AnoLancamento)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

JoaoSite/JoaoSite/Views/Modelo/Edit.cshtml
@model JoaoSite.Models.Modelo

@{
    ViewData["Title"] = "Editar";
}

<h1>Editar</h1>

<h4>Modelo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AnoLancamento" class="control-label"></label>
                <input asp-for="AnoLancamento" class="form-control" />
                <span asp-validation-for="AnoLancamento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MarcaId" class="control-label"></label>
                <select asp-for="MarcaId" class="form-control">
                    @foreach (var item in ViewBag.Marcas)
                    {
                        <option value="@item.Id">@item.Id - @item.Descricao</option>
                    }
                </select>
                <span asp-validation-for="MarcaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

JoaoSite/JoaoSite/Views/Modelo/Index.cshtml
@model IEnumerable<JoaoSite.Models.Modelo>

@{
    ViewData["Title"] = "Modelos Cadastrados";
}

    <h1>Modelos Cadastrados</h1>

<p>
    <button type="button" class="btn btn-success" onclick="location.href='@Url.Action("Create","Modelo")'">Criar Novo</button>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Descrição
            </th>
            <th>
                Ano de lançamento
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Descricao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AnoLancamento)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Detalhes</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Deletar</a>
            </td>
        </tr>
}
    </tbody>
</table>